name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Clean up previous containers
        run: |
          docker compose down --remove-orphans || true
          docker network rm labo03-network || true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Creer fichier .env
        run: |
          echo "DB_HOST=mysql" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo03_db" >> .env
          echo "DB_USER=labo03" >> .env
          echo "DB_PASS=labo03" >> .env
          echo "REDIS_HOST=redis" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Create Docker network
        run: docker network create labo03-network

      - name: Start Docker containers
        run: docker compose up -d

      - name: Wait for services to be ready
        run: sleep 15

      - name: Run tests
        working-directory: src
        run: docker exec store_manager python -m pytest -v
